// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PRUEBA1.Models;

public partial class Clientes
{
    [Key]
    public int pkclientes { get; set; }

    [Required]
    [StringLength(50)]
    public string nombre { get; set; }

    [Required]
    [StringLength(50)]
    public string apellido { get; set; }

    [Required]
    [StringLength(20)]
    public string cedula { get; set; }
}